# Generated by Django 4.2.2 on 2023-07-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scoring", "0002_relate_player_to_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="Displayable username accross the app",
        ),
        migrations.AddField(
            model_name="player",
            name="displayname",
            field=models.CharField(default="displayname", max_length=100),
            preserve_default=False,
        ),
    ]
