# Generated by Django 4.2.2 on 2023-07-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scoring", "0004_alter_player_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="role",
            field=models.CharField(
                choices=[("regular", "Regular"), ("editor", "Editor")],
                default="regular",
                max_length=20,
            ),
        ),
    ]
