# Generated by Django 4.2.2 on 2023-07-23 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scoring", "0006_remove_score_player_remove_board_player_scorer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="scoring.player"
            ),
        ),
    ]
