# Generated by Django 4.2.2 on 2023-08-08 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scoring", "0007_alter_board_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="scorer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="scoring.scorer"
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="scoring_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="scoring.scoringcategory",
            ),
        ),
    ]
