# Generated by Django 4.2.2 on 2023-08-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scoring", "0008_alter_score_scorer_alter_score_scoring_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="scorer",
            name="display_name",
            field=models.CharField(default="", max_length=5),
            preserve_default=False,
        ),
    ]
